server:
  port: 8081
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: secretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # Let Flyway handle schema changes
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

security:
  jwt:
    access-secret-b64:  "rXzZ72WfTUG6mhO7r9wZ69qJ5S8N2duU2to9Nw5a3mY="
    refresh-secret-b64: "m3cVvOdvptRzO2pnpqHgFfL6b+Kmtg5vFxt8jEsXXlw="
    access-ttl:  P1D  # 1 day
    refresh-ttl: P7D     # 7 days


logging:
  level:
    org.springframework.security: DEBUG


minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: miniosecret123
  region: us-east-1
  default-bucket: app-bucket
  presign:
    expiry: PT55M


